# Generated by Django 4.2.6 on 2023-10-14 17:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("genres", "0003_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="genre",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
