# Generated by Django 4.2.6 on 2023-10-15 04:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("genres", "0004_alter_genre_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="genre",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
