# Generated by Django 4.2.6 on 2023-12-05 19:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reviews", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="stars",
            field=models.IntegerField(
                validators=[
                    django.core.validators.MinValueValidator(
                        0, "Can't be less than 0 (zero) stars."
                    ),
                    django.core.validators.MaxValueValidator(
                        5, "Can't be greater than 5 (five) stars."
                    ),
                ]
            ),
        ),
    ]
