# Generated by Django 4.2.6 on 2023-10-22 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("actors", "0002_alter_actor_options"),
        ("genres", "0006_alter_genre_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="Movie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=500)),
                ("release_date", models.DateField(blank=True, null=True)),
                ("summary", models.TextField(blank=True, null=True)),
                (
                    "cast",
                    models.ManyToManyField(related_name="movies", to="actors.actor"),
                ),
                (
                    "genre",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="movies",
                        to="genres.genre",
                    ),
                ),
            ],
        ),
    ]
